FROM quay.io/keycloak/keycloak:26.0.7

COPY email-interceptor-mapper-1.0-SNAPSHOT.jar /opt/keycloak/providers/

COPY keycloak-to-rabbit-3.0.5.jar /opt/keycloak/providers/

COPY keycloak-to-rabbit.jar /opt/keycloak/providers/